kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_key
      registry: ghcr.io
      repo: ghcr.io/pxlblue/anticrash
      tags: ['${DRONE_COMMIT}', 'latest']
